

name: cowsay 


on:
  workflow_dispatch:

jobs:
  cowsay:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Cowsay package 
        run: |
          sudo apt-get update
          sudo apt-get install cowsay

      
      - name: Run a Cowsay command
        run: |
          cowsay "Hello, World!" > cowsay.txt
          cat cowsay.txt
