name: Job Concurency

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: staging_environment
      cancel-in-progress: false 
      #true or false if its true  existing running job cancle started running this, if false waiting for other job to complete
      
    steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          sleep 20
