name: Shell Script Run

on:
  workflow_dispatch:

jobs:
  script:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: given the permiision
        run: chmod 777 shelscript.sh
      # Runs a single command using the runners shell
      - name: Run a Shell Script script
        run: ./shelscript.sh

     
